### ISSUE TITLE
Fjerner for mye (på adressa.no

### ISSUE THREAD

**Issue by forteller** [NicTorgersen/skakkehanopluss#2]
Hei. Jeg testa akkurat denne i Firefox på adressa.no. Har ikke sjekket andre steder, så vet ikke om det er et større problem, men jeg oppdaget ihvertfall der at den også fjerner saker som ikke er pluss. Se følgende to skjermbilder:
![screenshot from 2018-02-18 01-57-01](https://user-images.githubusercontent.com/343561/36347123-2d4f6650-1447-11e8-93c5-1924855144bb.png)
![screenshot from 2018-02-18 01-57-19](https://user-images.githubusercontent.com/343561/36347124-4788bdf0-1447-11e8-8087-b21f29cb19ec.png)
Som du ser er det to artikler der som ikke er pluss, men likevel fjernes: "Huskelisten…" og "mystisk sykdom". Jeg har klikket meg inn på dem og bekreftet at de ikke er pluss-saker. Har også søkt på siden og sett at de ikke har blitt flyttet til et annet sted. Skjermbildene er tatt nå.

Alt godt!

**Comment by NicTorgersen** [comment]
Takk for feilrapport på GitHub!!!

Dette er fikset i c593dd4 , skal forsøke å få til en release denne uken :)
